#spring.data.mongodb.uri=mongodb+srv://aniketjain2522:Aniket123@cluster0.hvpbbpq.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
#spring.data.mongodb.database=journaldb
##spring.data.mongodb.username=xxx
##spring.data.mongodb.password=xxx
#spring.data.mongodb.auto-index-creation=true